version: '3'

services:
  fluentdbtools-abstractions-nuget: &fluentdbtools-nuget
    image: fluentdbtools.abstractions.nuget
    build:
      context: .
      dockerfile: Dockerfile_PublishNuget
      args:
        - VERSION=${VERSION}
        - PROJECT_FOLDER=FluentDbTools/Abstractions
        - API_KEY=${API_KEY}

  fluentdbtools-implementations-nuget:
    <<: *fluentdbtools-nuget
    image: fluentdbtools.implementations.nuget
    build:
      context: .
      dockerfile: Dockerfile_PublishNuget
      args:
        - VERSION=${VERSION}
        - PROJECT_FOLDER=FluentDbTools/Implementations
        - API_KEY=${API_KEY}

  fluentdbtools-extensions-nuget:
    <<: *fluentdbtools-nuget
    image: fluentdbtools.extensions.nuget
    build:
      context: .
      dockerfile: Dockerfile_PublishNuget
      args:
        - VERSION=${VERSION}
        - PROJECT_FOLDER=FluentDbTools/Extensions
        - API_KEY=${API_KEY}

  fluentdbtools-contracts-nuget:
    <<: *fluentdbtools-nuget
    image: fluentdbtools.contracts.nuget
    build:
      context: .
      dockerfile: Dockerfile_PublishNuget
      args:
        - VERSION=${VERSION}
        - PROJECT_FOLDER=FluentDbTools/Contracts
        - API_KEY=${API_KEY}